const Case09 = () => {
  return (
    <div className="case-study">
      <header className="case-header">
        <span className="case-number">Use Case 09</span>
        <h1>The Market That Looks Big but Isn&apos;t</h1>
        <div className="case-meta">
          Industry: Consumer / Geographic Expansion &bull; Level: Advanced / Strategic &mdash; C-Suite Market Entry &amp; Capital Allocation Decision
        </div>
      </header>

      <section>
        <h2>The Company That Wants to Go Everywhere</h2>
        <div className="content">
          <p>
            <strong>BrewStar</strong> is a Singapore-headquartered premium ready-to-drink (RTD) beverage company with <strong>SGD 480 million (~USD 355 million) in annual revenue</strong>, built on a portfolio of three core products: a craft-style sparkling tea, a functional hydration drink, and a premium cold brew coffee range. Founded in 2016 by two former Unilever brand managers, BrewStar has achieved strong market positions in Singapore (#1 in RTD premium tea), Malaysia (#2), and Hong Kong (#2), and generated SGD 68 million in EBITDA in the most recent financial year &mdash; a 14.2% margin that compares favourably against regional FMCG benchmarks.
          </p>
          <p>
            The company&apos;s Series C investors &mdash; a Singaporean sovereign wealth vehicle and a Hong Kong growth equity fund &mdash; have been pushing the CEO to accelerate geographic expansion since the round closed 18 months ago. The investment thesis at Series C was explicitly built on a Southeast Asia and South Asia expansion narrative: BrewStar would enter India, Vietnam, Thailand, and the Philippines over a 36-month horizon, building the regional scale that justifies either a strategic sale to a global beverage multinational or a dual-listing IPO in Singapore and Hong Kong.
          </p>
          <p>
            The CEO, <strong>Priscilla Tan</strong>, has been more cautious than the investors anticipated. She has watched several regional consumer brands burn capital on premature geographic expansion and is not convinced that all four target markets are equally attractive or equally ready. She has agreed to commit to two new market entries in the next 18 months but has insisted on a rigorous market prioritisation process before the capital is allocated. The board approved a consulting engagement to produce a market sizing and entry recommendation within six weeks.
          </p>
          <div className="highlight-box">
            <strong>The Risk That Priscilla Is Trying to Avoid</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              BrewStar&apos;s Series C valuation of SGD 1.2 billion was built on a revenue multiple applied to a growth story. The growth story requires geographic expansion. But geographic expansion at the wrong pace, in the wrong markets, or at insufficient depth burns capital without building the revenue that justifies the valuation. Priscilla has seen the pattern: a company enters three markets simultaneously, spreads its commercial team too thin, fails to achieve critical mass in any of them, and returns to investors 24 months later needing a bridge round to fund an expansion that was supposed to be self-funding by Month 18.
            </p>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Her specific concern: the investor deck at Series C used India&apos;s total addressable market (TAM) for premium beverages as a headline number &mdash; USD 14 billion by 2028. That number is technically accurate and commercially irrelevant. BrewStar cannot access USD 14 billion of Indian premium beverage market. It can access a fraction of it, determined by the distribution channels it can realistically build, the consumer segments it can actually reach, and the competitive set it would face in those channels. The gap between TAM and realistically serviceable market is where consumer brand expansions die.
            </p>
          </div>
          <p>
            BrewStar has <strong>SGD 180 million in available capital</strong> for expansion investment &mdash; a combination of Series C proceeds not yet deployed and the free cash flow generated by the Singapore and Malaysia operations. The board has set a constraint: no single market entry can commit more than SGD 60 million in the first 24 months, and at least one of the two priority markets must show positive EBITDA contribution within 18 months of launch.
          </p>
        </div>
      </section>

      <section>
        <h2>Who Is in the Room</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>CEO &mdash; Priscilla Tan:</strong> Operationally rigorous, data-driven, and privately skeptical of the India-first narrative that the investors have been pushing. She built the Singapore business from zero to SGD 480M in eight years by being disciplined about where BrewStar competed &mdash; premium modern trade channels, health-conscious urban consumers, and occasions where the product&apos;s quality differentiation could be experienced and charged for. She wants the expansion strategy to follow the same logic: go where the premium consumer exists, where the channel can carry the product, and where BrewStar can win without subsidising the market into existence.
          </div>
          <div className="highlight-box">
            <strong>CFO &mdash; David Ng:</strong> Focused on the 18-month positive EBITDA constraint. He has modelled the cash flow implications of simultaneous entry into three markets and concluded that it requires a bridge round. He supports the two-market approach but wants the two markets selected to maximise the probability of hitting the EBITDA timeline &mdash; which means favouring markets with established modern trade infrastructure, concentrated premium consumer segments, and shorter distribution build timelines over markets with higher long-term potential but longer time-to-revenue.
          </div>
          <div className="highlight-box">
            <strong>Chief Commercial Officer &mdash; Rajan Mehta:</strong> Originally from India, has been advocating internally for India as the first and largest market entry. His argument is emotional as much as analytical: India is the largest consumer market in the region, the premium beverage segment is the fastest-growing category in Indian FMCG, and BrewStar&apos;s product positioning maps well to the urban middle-class consumer in Tier 1 cities. He is not wrong about any of these things. He is potentially wrong about how long it takes and how much it costs to build a distribution network that reaches those consumers at a price point that works for BrewStar&apos;s margins.
          </div>
          <div className="highlight-box">
            <strong>Series C Lead Investor &mdash; Aditya Krishnamurthy (Observer seat):</strong> Represents the sovereign wealth vehicle. He has been public-market-trained and is accustomed to thinking about market opportunity in terms of TAM, SAM, and growth rates &mdash; the metrics that populate investor decks. He is uncomfortable with the granular, bottom-up market sizing approach the consulting team is proposing because it will almost certainly produce smaller numbers than the top-down TAM slides he has been presenting to his investment committee. The consulting team must produce an analysis that is honest about the size of the real opportunity without making the investor feel that the deal thesis was fraudulent &mdash; because it was not; the TAM is genuinely large. The realistically serviceable market is just much smaller than TAM, and the distinction is not fraud, it is precision.
          </div>
        </div>
      </section>

      <section>
        <h2>The Problem, Precisely Defined</h2>
        <div className="content">
          <p>
            The presenting question is &ldquo;which two markets should BrewStar enter first?&rdquo; The actual analytical challenge is more fundamental: <strong>what is the realistic revenue opportunity for BrewStar in each target market, defined not as the total addressable market for premium beverages but as the market that BrewStar can actually reach, serve, and win given its product positioning, price point, distribution model, and capital constraints?</strong>
          </p>
          <p>
            The distinction between TAM and realistically serviceable market (RSM) is the most important analytical concept in consumer brand geographic expansion. TAM is what you show investors to justify the size of the opportunity. RSM is what you build your P&amp;L on. The gap between the two is determined by: the distribution channels BrewStar can actually access (modern trade hypermarkets, convenience chains, premium food service &mdash; not general trade), the consumer segments within those channels who are willing to pay BrewStar&apos;s price point, the geographic concentration of those consumers (urban Tier 1 cities, not national coverage), and the competitive intensity from local and multinational incumbents already serving those channels.
          </p>
          <div className="highlight-box">
            <strong>The Precise Problem Statement</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <em>Which two of the four target markets &mdash; India, Vietnam, Thailand, and the Philippines &mdash; offer the combination of realistic serviceable market size, time-to-positive-EBITDA, and capital efficiency that maximises BrewStar&apos;s return on its SGD 180 million expansion budget while building the regional scale the Series C thesis requires?</em>
            </p>
          </div>
          <p><strong>Four questions structure the engagement:</strong></p>
          <ol>
            <li><strong>What is the realistic serviceable market in each country</strong> &mdash; built bottom-up from distribution channel capacity, consumer segment size, and achievable price point, not top-down from category TAM?</li>
            <li><strong>What are the economics of market entry in each country</strong> &mdash; distribution build cost, working capital requirements, time-to-first-revenue, and the trajectory to positive EBITDA contribution?</li>
            <li><strong>What is the competitive intensity in BrewStar&apos;s specific channels and price tier</strong> &mdash; not the overall premium beverage market, but the exact shelf position and occasion BrewStar would occupy?</li>
            <li><strong>Which two markets generate the required return on SGD 60 million each within 24 months</strong> while leaving SGD 60 million in reserve for the second wave of entries?</li>
          </ol>
        </div>
      </section>

      <section>
        <h2>Analytical Frameworks</h2>
        <div className="content">

          <h3 style={{ fontSize: '17px', marginTop: '16px', marginBottom: '10px' }}>Framework 1 &mdash; Bottom-Up Market Sizing: TAM &rarr; SAM &rarr; RSM &rarr; BrewStar Target</h3>
          <p>
            The standard market sizing funnel moves from Total Addressable Market (everyone who could theoretically buy the product) to Serviceable Addressable Market (the portion reachable through the intended channels) to Realistically Serviceable Market (the portion reachable given specific capital and capability constraints) to the company&apos;s realistic market share target within the RSM. For BrewStar, each funnel stage is driven by a specific constraint:
          </p>
          <p>
            TAM to SAM: premium beverage consumers who shop in modern trade channels (hypermarkets, supermarkets, convenience chains, premium food service). In India, this eliminates approximately 78% of the TAM immediately &mdash; most premium beverage consumption either happens in food service channels that BrewStar cannot cost-effectively serve at launch, or in traditional trade channels where BrewStar&apos;s premium price point does not hold.
          </p>
          <p>
            SAM to RSM: the portion of the modern trade SAM reachable within BrewStar&apos;s 24-month distribution build. Distribution in consumer goods is built city by city, retailer by retailer, with meaningful working capital requirements at each stage. A SGD 60 million entry budget supports a specific number of cities and a specific retailer network. The RSM is defined by what that budget can reach, not by the total modern trade market in the country.
          </p>
          <p>
            RSM to BrewStar target: the market share BrewStar can realistically achieve in the RSM within 24 months, given the competitive set, its brand equity (zero in new markets), and the rate of consumer trial and repeat that its marketing investment can drive.
          </p>

          <h3 style={{ fontSize: '17px', marginTop: '20px', marginBottom: '10px' }}>Framework 2 &mdash; Porter&apos;s Five Forces Applied to the Specific Channel and Price Tier</h3>
          <p>
            Porter&apos;s Five Forces is typically applied at the industry level. For a market entry decision, it must be applied at the specific competitive arena &mdash; in BrewStar&apos;s case, the premium RTD beverage shelf in modern trade retail at a price point of SGD 3.50&ndash;5.00 per unit (adjusted for local purchasing power parity). At that level of specificity, the five forces analysis produces actionable conclusions: which markets have high barriers from established premium brands, which have fragmented local competition that BrewStar can displace, which have powerful retailers who extract margin from premium brands, and which have distribution structures that make new entrant shelf access genuinely difficult versus merely expensive.
          </p>

          <h3 style={{ fontSize: '17px', marginTop: '20px', marginBottom: '10px' }}>Framework 3 &mdash; Entry Economics Model: Time-to-EBITDA by Market</h3>
          <p>
            For each market, the team builds a 36-month P&amp;L projection: revenue ramp from distribution build, gross margin (product cost plus inbound logistics plus local distribution margin), marketing investment required to drive trial, fixed overhead for the local commercial team, and the resulting EBITDA contribution trajectory. The model identifies when each market crosses from negative to positive EBITDA contribution &mdash; the metric the CFO has made the binding constraint.
          </p>

          <table className="data-table" style={{ marginTop: '20px' }}>
            <thead>
              <tr>
                <th>Framework</th>
                <th>Question</th>
                <th>Output</th>
                <th>Why TAM Alone Fails Here</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Bottom-up RSM sizing</strong></td>
                <td>How big is the market BrewStar can actually reach?</td>
                <td>RSM by country and city tier, with funnel loss at each stage</td>
                <td>TAM includes channels and segments BrewStar cannot serve at launch</td>
              </tr>
              <tr>
                <td><strong>Porter&apos;s Five Forces (channel-specific)</strong></td>
                <td>How hard is it to win in the specific competitive arena?</td>
                <td>Competitive intensity score by market</td>
                <td>Industry-level forces miss channel-specific dynamics that determine shelf access</td>
              </tr>
              <tr>
                <td><strong>Entry economics model</strong></td>
                <td>When does each market become EBITDA positive?</td>
                <td>Month-by-month P&amp;L by market, EBITDA breakeven date</td>
                <td>TAM says nothing about the capital required or the timeline to return</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2>The Data: Four Markets, Four Different Realities</h2>
        <div className="content">

          <p><strong>TAM vs. Realistically Serviceable Market &mdash; The Funnel:</strong></p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Market</th>
                <th>Premium RTD TAM (2026, USD B)</th>
                <th>Modern Trade SAM (USD B)</th>
                <th>RSM at SGD 60M Budget (USD M)</th>
                <th>RSM as % of TAM</th>
                <th>BrewStar Target Share (Yr 2)</th>
                <th>BrewStar Target Revenue (Yr 2, USD M)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>India</strong></td>
                <td>USD 14.2B</td>
                <td>USD 2.8B</td>
                <td>USD 180M</td>
                <td>1.3%</td>
                <td>4&ndash;6%</td>
                <td>USD 7&ndash;11M</td>
              </tr>
              <tr>
                <td><strong>Vietnam</strong></td>
                <td>USD 1.8B</td>
                <td>USD 0.62B</td>
                <td>USD 148M</td>
                <td>8.2%</td>
                <td>6&ndash;9%</td>
                <td>USD 9&ndash;13M</td>
              </tr>
              <tr>
                <td><strong>Thailand</strong></td>
                <td>USD 2.4B</td>
                <td>USD 0.94B</td>
                <td>USD 224M</td>
                <td>9.3%</td>
                <td>5&ndash;8%</td>
                <td>USD 11&ndash;18M</td>
              </tr>
              <tr>
                <td><strong>Philippines</strong></td>
                <td>USD 1.2B</td>
                <td>USD 0.38B</td>
                <td>USD 92M</td>
                <td>7.7%</td>
                <td>7&ndash;10%</td>
                <td>USD 6&ndash;9M</td>
              </tr>
            </tbody>
          </table>

          <p style={{ marginTop: '20px' }}><strong>Competitive Intensity &mdash; Premium RTD Shelf in Modern Trade:</strong></p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Force</th>
                <th>India</th>
                <th>Vietnam</th>
                <th>Thailand</th>
                <th>Philippines</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Incumbent rivalry</strong></td>
                <td>High &mdash; Coca-Cola, PepsiCo, Tata, ITC all invested in premium RTD</td>
                <td>Medium &mdash; fragmented local brands, Suntory/Asahi growing</td>
                <td>Medium-High &mdash; Ichitan dominant, Oishi strong, Thai Beverages vertically integrated</td>
                <td>Low-Medium &mdash; fragmented, no dominant premium RTD brand</td>
              </tr>
              <tr>
                <td><strong>Retailer power</strong></td>
                <td>Very High &mdash; modern trade dominated by Reliance Retail, DMart; listing fees significant</td>
                <td>Medium &mdash; VinMart/WinMart consolidating; Co.opmart accessible</td>
                <td>Medium &mdash; Lotus&apos;s, Big C, 7-Eleven; structured but manageable listing terms</td>
                <td>Medium &mdash; SM Supermarkets, Robinsons; fragmented enough for negotiation</td>
              </tr>
              <tr>
                <td><strong>Distribution barriers</strong></td>
                <td>Very High &mdash; cold chain logistics outside Tier 1 cities unreliable; distributor fragmentation severe</td>
                <td>Low-Medium &mdash; Ho Chi Minh City and Hanoi have functional cold chain; distributors accessible</td>
                <td>Low &mdash; Bangkok has excellent modern trade infrastructure; 7-Eleven coverage 14,000 stores</td>
                <td>Medium &mdash; Metro Manila accessible; Visayas/Mindanao require separate distributor relationships</td>
              </tr>
              <tr>
                <td><strong>Consumer willingness to pay premium</strong></td>
                <td>Medium &mdash; urban Tier 1 high; Tier 2 significantly lower; BrewStar price point is at upper limit</td>
                <td>Medium-High &mdash; young urban consumers in HCMC and Hanoi willing to pay; growing premiumisation</td>
                <td>High &mdash; Bangkok consumer well-established in premium RTD; health beverage segment growing fast</td>
                <td>Medium &mdash; Manila premium consumer exists; smaller segment than Thailand or Vietnam</td>
              </tr>
              <tr>
                <td><strong>New entrant threat to BrewStar</strong></td>
                <td>High &mdash; local brands can undercut on price; MNCs can outspend on marketing</td>
                <td>Low &mdash; premium RTD segment underdeveloped; first-mover advantage real</td>
                <td>Medium &mdash; established players will respond; but premium functional segment is relatively open</td>
                <td>Low-Medium &mdash; limited premium competition in BrewStar&apos;s specific tiers</td>
              </tr>
              <tr>
                <td><strong>Overall competitive intensity</strong></td>
                <td><strong>Very High</strong></td>
                <td><strong>Low-Medium</strong></td>
                <td><strong>Medium</strong></td>
                <td><strong>Low-Medium</strong></td>
              </tr>
            </tbody>
          </table>

          <p style={{ marginTop: '20px' }}><strong>Entry Economics Summary &mdash; SGD 60M Budget per Market:</strong></p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Parameter</th>
                <th>India</th>
                <th>Vietnam</th>
                <th>Thailand</th>
                <th>Philippines</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Distribution build cost (Yr 1)</td>
                <td>SGD 28M</td>
                <td>SGD 12M</td>
                <td>SGD 14M</td>
                <td>SGD 10M</td>
              </tr>
              <tr>
                <td>Marketing (trial &amp; awareness, Yr 1)</td>
                <td>SGD 18M</td>
                <td>SGD 8M</td>
                <td>SGD 10M</td>
                <td>SGD 7M</td>
              </tr>
              <tr>
                <td>Commercial team &amp; overhead (Yr 1)</td>
                <td>SGD 8M</td>
                <td>SGD 4M</td>
                <td>SGD 5M</td>
                <td>SGD 4M</td>
              </tr>
              <tr>
                <td>Working capital (inventory buffer)</td>
                <td>SGD 9M</td>
                <td>SGD 4M</td>
                <td>SGD 5M</td>
                <td>SGD 3M</td>
              </tr>
              <tr>
                <td><strong>Total Year 1 investment</strong></td>
                <td><strong>SGD 63M</strong></td>
                <td><strong>SGD 28M</strong></td>
                <td><strong>SGD 34M</strong></td>
                <td><strong>SGD 24M</strong></td>
              </tr>
              <tr>
                <td>First revenue (months)</td>
                <td>8&ndash;12</td>
                <td>4&ndash;6</td>
                <td>3&ndash;5</td>
                <td>4&ndash;6</td>
              </tr>
              <tr>
                <td>EBITDA breakeven (months)</td>
                <td>28&ndash;36+</td>
                <td>14&ndash;18</td>
                <td>12&ndash;16</td>
                <td>16&ndash;20</td>
              </tr>
              <tr>
                <td>Year 2 revenue (base case, SGD M)</td>
                <td>SGD 14&ndash;18M</td>
                <td>SGD 22&ndash;28M</td>
                <td>SGD 32&ndash;42M</td>
                <td>SGD 12&ndash;16M</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2>The Calculations</h2>
        <div className="content">

          <p><strong>Calculation 1 &mdash; India RSM: How USD 14.2B Becomes USD 180M</strong></p>
          <div className="calculation">
{`India TAM to RSM waterfall:

Step 1 \u2014 Total Addressable Market (premium RTD beverages, India, 2026):
  Market research estimate:               USD 14.2B
  Note: includes ALL premium beverage categories (RTD tea, functional drinks,
  premium water, cold brew coffee, kombucha, premium juice) across
  ALL retail channels (modern trade, traditional trade, food service, e-commerce)
  across ALL of India (800+ cities, 28 states).
  This is the number in the investor deck.

Step 2 \u2014 Serviceable Addressable Market (modern trade only):
  Traditional trade exclusion: 68% of premium RTD sold through kiranas and
  small retailers where BrewStar\apos;s price point (INR 120\u2013180) is
  uncompetitive against local premium brands (INR 60\u201380).
  Food service exclusion: 14% sold through cafes/restaurants requiring
  direct sales force BrewStar cannot afford to build at launch.
  BrewStar-relevant categories only (sparkling tea, functional, cold brew):
  18% of premium RTD TAM is in BrewStar\apos;s specific categories.
  Modern trade SAM: USD 14.2B \xd7 32% (modern trade) \xd7 18% (category) = USD 0.82B
  \u2026 wait, investor deck uses USD 2.8B SAM. Let\apos;s reconcile:
  Investor deck SAM includes categories BrewStar does not compete in.
  Corrected SAM (BrewStar-relevant categories, modern trade): USD 0.82B

Step 3 \u2014 Realistically Serviceable Market (RSM) at SGD 60M budget:
  Geographic scope: SGD 60M supports Tier 1 cities only
    Mumbai, Delhi, Bengaluru, Hyderabad, Chennai, Pune: 6 cities
    6 cities represent 22% of modern trade volume in India
  RSM: USD 0.82B \xd7 22% = USD 0.18B = USD 180M  (matches table)

Step 4 \u2014 BrewStar realistic share in RSM:
  New entrant in India with no brand equity: 2\u20133 years to establish
  Competitive set: ITC B Natural, Raw Pressery (Coca-Cola), Paperboat (Hector)
    all established in modern trade with shelf positioning and retailer relationships
  Realistic Year 2 share: 4\u20136% of RSM
  BrewStar Year 2 revenue (India): USD 180M \xd7 5% = USD 9M

  The investor narrative: "India\apos;s USD 14.2B premium beverage TAM"
  The commercial reality: "USD 9M Year 2 revenue target"
  The ratio: USD 9M \xf7 USD 14.2B = 0.063% of TAM

  At 14.2% EBITDA margin (BrewStar\apos;s current margin):
  Year 2 EBITDA contribution (India): USD 9M \xd7 14.2% = USD 1.3M
  Year 1 investment (India): SGD 63M \u2248 USD 46M
  Return on investment (Year 2): USD 1.3M \xf7 USD 46M = 2.8%

  For context: a 10-year Singapore government bond yields ~3.2%.
  The India investment in Year 2 returns less than the risk-free rate.
  And it has already exceeded the SGD 60M per-market budget.

  \u27f9 India\apos;s market is genuinely large.
     BrewStar\apos;s accessible portion is genuinely small.
     The economics in Year 2 do not justify the investment.
     The right time to enter India is Year 4\u20135, when BrewStar
     has the brand equity, distribution infrastructure, and
     cash flow from the established markets to fund a proper entry.`}
          </div>

          <p style={{ marginTop: '20px' }}><strong>Calculation 2 &mdash; Thailand RSM and Entry Economics: The Priority Market</strong></p>
          <div className="calculation">
{`Thailand market sizing:

TAM (premium RTD, Thailand, 2026):         USD 2.4B
  Modern trade share:                        58%
  BrewStar-relevant categories:             24%
  SAM:                                     USD 2.4B \xd7 58% \xd7 24% = USD 0.33B

RSM at SGD 60M budget:
  Geographic scope: Bangkok + Chiang Mai + Phuket (top 3 premium markets)
  These 3 markets hold 71% of Thailand\apos;s modern trade premium RTD volume
  7-Eleven presence: 14,000 stores (highest convenience store density in SEA)
  Premium supermarkets: Tops, Gourmet Market, Villa Market (240 stores combined)
  RSM: USD 0.33B \xd7 71% = USD 0.24B  (Table shows USD 224M \u2714)

BrewStar Year 2 target: 6% RSM share = USD 0.24B \xd7 6% = USD 14.4M

Thailand entry economics (SGD 60M budget):
  Year 1 investment: SGD 34M
  Investment allocation:
    7-Eleven listing fee + merchandising:    SGD  5.2M
    Premium supermarket listings:            SGD  3.8M
    Cold chain distribution build:           SGD  5.0M
    Marketing (sampling, digital, OOH Bangkok): SGD 10.0M
    Commercial team (20 headcount):          SGD  5.0M
    Working capital (8-week inventory):      SGD  5.0M
    Total Year 1:                            SGD 34.0M  \u2714 within SGD 60M budget

Revenue ramp (SGD M):
  Month 1\u20133: distribution build (no revenue)
  Month 4: first revenue from pilot stores (12 7-Eleven + 8 premium supermarkets)
  Month 5\u20136: expansion to 200 7-Eleven + 40 premium supermarkets
  Month 8: Bangkok distribution complete (1,400 7-Eleven + 80 supermarkets)
  Month 10: Chiang Mai and Phuket entry
  Month 12: SGD 4.2M revenue (annualised rate: SGD 8.4M \u2014 38% penetration of target)
  Month 18: SGD 6.8M revenue (annualised: SGD 13.6M \u2248 Year 2 target)

  Monthly P&L (Month 13, representative):
    Revenue:                                SGD 0.57M
    COGS (product + inbound + local dist.): SGD 0.34M  (59.6% of revenue)
    Gross margin:                           SGD 0.23M  (40.4%)
    Marketing (reduced from launch):        SGD 0.12M
    Overhead (team + facilities):           SGD 0.09M
    Monthly EBITDA contribution:            SGD 0.02M  (first positive month)
  EBITDA breakeven: Month 13\u201315  \u2714 Within 18-month constraint

  Year 2 P&L (full year):
    Revenue:                               SGD 36M  (USD 26M, above USD 14M target)
    Gross margin (42%):                    SGD 15.1M
    Marketing + overhead:                  SGD 9.2M
    EBITDA contribution:                   SGD 5.9M  (16.4% margin)
    Year 2 cumulative investment:          SGD 52M  (under SGD 60M cap)

  \u27f9 Thailand hits all three of Priscilla\apos;s constraints:
     (1) Under SGD 60M total 24-month investment \u2713
     (2) EBITDA positive within 18 months (Month 13\u201315) \u2713
     (3) RSM of USD 224M with clear path to USD 26M revenue \u2713
     Thailand is Priority Market 1.`}
          </div>

          <p style={{ marginTop: '20px' }}><strong>Calculation 3 &mdash; Vietnam RSM and Entry Economics: The Second Priority</strong></p>
          <div className="calculation">
{`Vietnam market sizing:

TAM (premium RTD, Vietnam, 2026):          USD 1.8B
  Modern trade + premium food service:      41%
  BrewStar-relevant categories:            22%
  SAM:                                    USD 1.8B \xd7 41% \xd7 22% = USD 0.162B

RSM at SGD 60M budget:
  Ho Chi Minh City + Hanoi: 68% of premium modern trade volume
  RSM: USD 0.162B \xd7 68% = USD 0.110B  (\u2248 USD 148M including food service; table reconciled)

First-mover advantage assessment:
  Premium RTD tea and functional drinks underdeveloped in Vietnam.
  Local market dominated by TH True Milk (dairy-adjacent) and
  imported Korean/Japanese products at higher price points.
  BrewStar at VND 45,000\u201365,000 (SGD 2.60\u20133.80) per unit positions
  below Japanese imports (VND 80,000+) and above local brands (VND 20,000\u201330,000).
  This mid-premium tier is underserved. First-mover who owns it
  builds a defensible position before MNCs enter at scale.

BrewStar Year 2 target: 7.5% RSM share = USD 148M \xd7 7.5% = USD 11.1M

Vietnam entry economics:
  Year 1 investment: SGD 28M
    WinMart/VinMart listing + distribution:  SGD  4.8M
    Co.opmart and independent premium:        SGD  2.4M
    Food service (premium cafes, HCMC):       SGD  3.2M
    Cold chain distribution (HCMC + Hanoi):  SGD  4.8M
    Marketing (digital heavy \u2014 Vietnam skews young/digital): SGD  8.0M
    Commercial team (16 headcount):           SGD  3.6M
    Working capital:                          SGD  1.2M
    Total Year 1:                            SGD 28.0M  \u2714 well within budget

Revenue ramp:
  Month 4: first revenue from HCMC modern trade (120 stores)
  Month 8: Hanoi entry + food service expansion (40 premium cafes)
  Month 12: SGD 2.8M revenue (annualised: SGD 5.6M)
  Month 16: SGD 4.2M revenue (annualised: SGD 10.1M \u2248 target)

  EBITDA breakeven: Month 15\u201318  \u2714 Meets 18-month constraint (tight)

  Year 2 P&L:
    Revenue:                               SGD 22M  (USD 16M \u2014 above USD 11M target)
    Gross margin (41%):                    SGD 9.0M
    Marketing + overhead:                  SGD 5.8M
    EBITDA contribution:                   SGD 3.2M  (14.5% margin)
    Year 2 cumulative investment:          SGD 42M  (comfortably within SGD 60M)

Vietnam vs. Thailand comparison:
  RSM:                 VN: USD 148M  vs.  TH: USD 224M  (Thailand 51% larger RSM)
  Year 2 revenue:      VN: SGD 22M   vs.  TH: SGD 36M   (Thailand 64% more revenue)
  Year 1 investment:   VN: SGD 28M   vs.  TH: SGD 34M   (Vietnam 18% cheaper)
  EBITDA breakeven:    VN: Month 15\u201318 vs. TH: Month 13\u201315 (Thailand faster)
  Competitive risk:    VN: Low-Medium vs. TH: Medium  (Vietnam slightly less competitive)
  First-mover value:   VN: HIGH      vs.  TH: Medium  (Vietnam uncrowded premium tier)

  \u27f9 Vietnam is the better risk-adjusted choice for Priority Market 2.
     Lower investment, first-mover advantage in an underdeveloped premium tier,
     and a digital-native young consumer base that builds brand faster.
     Thailand has higher revenue ceiling but more competition.
     The combination of Thailand (higher revenue) + Vietnam (first-mover)
     is superior to Thailand + Philippines (similar revenue, no first-mover).`}
          </div>

          <p style={{ marginTop: '20px' }}><strong>Calculation 4 &mdash; Philippines: Why It Misses the Constraint</strong></p>
          <div className="calculation">
{`Philippines market sizing:

RSM at SGD 60M budget: USD 92M  (smallest of the four markets)
Year 2 revenue target: USD 92M \xd7 8.5% = USD 7.8M \u2248 SGD 11M

Philippines entry economics:
  Year 1 investment: SGD 24M
  Revenue ramp: Month 4 first revenue (SM Supermarkets, Robinsons)
  EBITDA breakeven: Month 16\u201320  \u2717 Misses 18-month constraint (tight end)

  Why Philippines underperforms the constraint:
  (1) RSM is USD 92M \u2014 smallest of four markets. Metro Manila\apos;s
      premium modern trade is well-developed but geographically compact.
      Beyond Metro Manila, Cebu and Davao require separate distributor
      relationships that the SGD 24M Year 1 budget cannot fund.
  (2) SM Group and Robinsons Retail are powerful retailers who extract
      significant listing fees from new premium brands. Entry cost per
      door is higher than Vietnam despite smaller total market.
  (3) No first-mover advantage. Del Monte Philippines, Zest-O, and
      Monde Nissin all have premium RTD variants. The tier is more
      competitive than the overall market intensity suggests.

  Philippines Year 2 P&L:
    Revenue:                             SGD 14M
    Gross margin (40%):                  SGD 5.6M
    Marketing + overhead:                SGD 5.1M
    EBITDA contribution:                 SGD 0.5M  (3.6% margin \u2014 barely positive)
    EBITDA breakeven: Month 17\u201319  \u2717 Misses 18-month constraint for most scenarios

  Philippines vs. Vietnam:
    Revenue (Yr 2):   PH: SGD 14M  vs.  VN: SGD 22M  (Vietnam 57% more)
    RSM:              PH: USD 92M  vs.  VN: USD 148M  (Vietnam 61% larger)
    EBITDA breakeven: PH: Month 17\u201319 vs. VN: Month 15\u201318
    First-mover:      PH: Low      vs.  VN: High

  \u27f9 Philippines is the third-priority market.
     It does not fail outright \u2014 it simply underperforms Vietnam
     on every metric that matters to Priscilla\apos;s constraints.
     Sequence: Thailand \u2192 Vietnam (now) \u2192 Philippines (Year 3)
     when the commercial team has the bandwidth and the brand
     has regional credibility to accelerate the Philippines launch.`}
          </div>

          <p style={{ marginTop: '20px' }}><strong>Calculation 5 &mdash; Capital Allocation and Portfolio Return</strong></p>
          <div className="calculation">
{`Capital allocation: SGD 180M available

Priority 1 \u2014 Thailand (immediate):
  24-month investment:     SGD 52M
  Year 2 revenue:          SGD 36M
  Year 2 EBITDA:           SGD 5.9M
  Year 3 EBITDA (est.):    SGD 12.4M  (full-year ramp to peak share)

Priority 2 \u2014 Vietnam (immediate, 2 months offset):
  24-month investment:     SGD 42M
  Year 2 revenue:          SGD 22M
  Year 2 EBITDA:           SGD 3.2M
  Year 3 EBITDA (est.):    SGD 7.8M

Priority 3 \u2014 Philippines (Year 2 entry, pending Thailand/Vietnam success):
  Reserved capital:        SGD 46M  (SGD 180M \u2212 52M \u2212 42M \u2212 40M reserve)
  Year 3 investment:       SGD 30M  (smaller launch, brand equity from regional presence)
  Year 3 EBITDA:           SGD 0.8M (partial year)

Reserve:
  SGD 40M kept as liquidity buffer and India exploration fund.
  India: SGD 20M allocated for feasibility work, regulatory navigation,
  and a small-scale test launch (Mumbai only, 50 outlets) to build
  the knowledge base for a proper entry in Year 4\u20135.
  Remaining reserve: SGD 20M operating buffer.

Combined portfolio return (Thailand + Vietnam, Year 3):
  Thailand Year 3 EBITDA:  SGD 12.4M
  Vietnam Year 3 EBITDA:   SGD  7.8M
  Combined EBITDA:          SGD 20.2M
  Total investment to Year 3: SGD 94M
  Return on expansion capital: SGD 20.2M \xf7 SGD 94M = 21.5%/yr  \u2713
  Revenue contribution (Year 3): SGD 58M + SGD 34M = SGD 92M
  vs. BrewStar current revenue: SGD 480M
  New revenue as % of current:  +19.2%  \u2014 meaningful, not transformative

Investor narrative re-frame:
  Series C thesis: "BrewStar enters 4 markets in 36 months, USD 14.2B TAM"
  Revised thesis:  "BrewStar enters 2 markets in 18 months at 21.5% ROIC,
                    generates SGD 92M in new revenue by Year 3,
                    preserves SGD 86M for Philippines (Year 3) and
                    India (Year 4) entries from a position of strength"

  The revised thesis generates better returns, lower risk, and
  stronger exit story than the original 4-market simultaneous plan.
  A company with proven multi-market execution in two markets is
  worth more to a strategic acquirer than a company that has
  attempted four markets and succeeded partially in none.

  \u27f9 Thailand + Vietnam is the answer.
     India is the answer in Year 4\u20135, not Year 1.
     The investor needs to hear this not as a reduction
     of ambition but as a refinement of execution.`}
          </div>
        </div>
      </section>

      <section>
        <h2>Findings</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>Finding 1 &mdash; India&apos;s USD 14.2B TAM Translates to USD 9M in Year 2 Revenue for BrewStar</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              The TAM is real and large. BrewStar&apos;s realistic serviceable market in India at a SGD 60M budget is USD 180M &mdash; 1.3% of TAM. At a realistic 5% share of that RSM, Year 2 revenue is USD 9M. The India entry also exceeds the SGD 60M per-market budget (requires SGD 63M in Year 1 alone), misses the 18-month EBITDA breakeven constraint by 10&ndash;18 months, and faces the most intense competitive environment of the four markets. India is the right market in Year 4&ndash;5 when BrewStar has regional brand equity, operational experience, and the cash flow to fund a proper Tier 1 city rollout. It is the wrong market in Year 1.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Finding 2 &mdash; Thailand Is the Priority Market on Every Metric That Matters</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Thailand has the largest RSM of the four markets (USD 224M), the fastest EBITDA breakeven (Month 13&ndash;15), the best modern trade infrastructure in Southeast Asia (14,000 7-Eleven stores), and a Bangkok consumer who is already habituated to premium RTD beverages. The Year 1 investment of SGD 34M is within budget and the Year 2 revenue of SGD 36M exceeds the USD 14M target. There is no analytical scenario in which Thailand is not the first priority market.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Finding 3 &mdash; Vietnam Offers First-Mover Advantage in an Underdeveloped Premium Tier</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Vietnam&apos;s mid-premium RTD tier &mdash; priced below Japanese imports but above local brands &mdash; is genuinely underserved. The first premium RTD brand to establish distribution across WinMart, Co.opmart, and the HCMC food service channel owns the positioning before MNCs arrive at scale. BrewStar&apos;s products map well to the young, digitally engaged urban Vietnamese consumer. The SGD 28M Year 1 investment is the lowest of all four markets, and the 21.5% combined ROIC on the Thailand-Vietnam portfolio is the strongest achievable configuration within the capital constraints.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Finding 4 &mdash; Philippines Is Third, Not Fourth &mdash; But Not Now</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              The Philippines is a credible market with a real premium consumer segment in Metro Manila. Its RSM of USD 92M and EBITDA breakeven of Month 17&ndash;19 make it a Year 3 entry, not a Year 1 entry. Entering the Philippines in Year 3 with regional brand credibility from Thailand and Vietnam will require less marketing investment, generate faster retailer acceptance, and hit breakeven faster than a cold-start entry now. The sequencing preserves the opportunity without rushing it.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Finding 5 &mdash; The Investor&apos;s TAM Narrative Is Not Wrong, It Is Incomplete</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Aditya Krishnamurthy&apos;s USD 14.2B India TAM is a real market size estimate. The problem is not that it is inaccurate &mdash; it is that it is irrelevant to BrewStar&apos;s capital allocation decision in Year 1. The distinction between TAM and RSM is not a challenge to the investment thesis. It is the mechanism by which the investment thesis gets executed without burning capital on markets BrewStar cannot yet serve. The investor needs to hear: &ldquo;India is in the plan. It is in Year 4&ndash;5, when BrewStar arrives with regional brand equity and operational proof points, and can command shelf space and retailer attention that a cold entry cannot.&rdquo;
            </p>
          </div>
        </div>
      </section>

      <section>
        <h2>Recommendations</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>R1. Approve Thailand as Priority Market 1 &mdash; Launch Immediately</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <strong>What:</strong> Commit SGD 34M Year 1 investment to Thailand. Begin 7-Eleven and premium supermarket listing negotiations this quarter. Hire Country Manager (Thailand) within 60 days. Target first revenue in Month 4&ndash;5.
              <br /><strong>Year 1 milestones:</strong> 1,400 7-Eleven stores listed by Month 8; 80 premium supermarket doors by Month 6; Bangkok distribution complete by Month 9; Chiang Mai and Phuket by Month 11.
              <br /><strong>EBITDA target:</strong> Positive contribution by Month 13&ndash;15. If not achieved by Month 16, review distribution model before committing Year 2 incremental budget.
              <br /><strong>Owner:</strong> CCO Rajan Mehta + Thailand Country Manager (to be hired).
            </p>
          </div>
          <div className="highlight-box">
            <strong>R2. Approve Vietnam as Priority Market 2 &mdash; Launch Two Months Behind Thailand</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <strong>What:</strong> Commit SGD 28M Year 1 investment to Vietnam. Stagger launch 8 weeks behind Thailand to allow the commercial team to establish the Thailand operation before splitting attention.
              <br /><strong>First-mover strategy:</strong> Prioritise WinMart and Co.opmart listings in Ho Chi Minh City (Month 4&ndash;5), food service channel in Pham Ngu Lao and District 1 (Month 5&ndash;6), Hanoi entry (Month 8). Digital-first marketing &mdash; Vietnam&apos;s premium consumer discovery is 74% digital.
              <br /><strong>EBITDA target:</strong> Positive contribution by Month 15&ndash;18.
              <br /><strong>Owner:</strong> CCO + Vietnam Country Manager (to be hired).
            </p>
          </div>
          <div className="highlight-box">
            <strong>R3. Allocate SGD 20M to India Feasibility and Test Launch &mdash; Not a Full Entry</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <strong>What:</strong> Deploy SGD 20M over 24 months for India market preparation: regulatory filing (FSSAI approval process), 50-outlet test launch in Mumbai premium supermarkets, distributor relationship building, and brand awareness seeding through digital and food service channels.
              <br /><strong>Why:</strong> BrewStar needs to begin building brand awareness and regulatory compliance in India now, even though the full entry is Year 4&ndash;5. The 24&ndash;36 month lead time for FSSAI approval and distributor network development means work must start in Year 1 for Year 4 entry to be realistic.
              <br /><strong>What this is not:</strong> A full market entry. 50 outlets is a learning exercise, not a commercial commitment.
            </p>
          </div>
          <div className="highlight-box">
            <strong>R4. Communicate Revised Expansion Thesis to Investors Before Board Meeting</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <strong>What:</strong> Priscilla to meet Aditya Krishnamurthy privately before the board presentation. Share the RSM analysis for India, the Thailand and Vietnam entry plans, and the capital allocation model. Frame as: &ldquo;We are executing the Series C thesis with greater precision, not less ambition.&rdquo;
              <br /><strong>The investor concern to pre-empt:</strong> He will read &ldquo;India deferred&rdquo; as a weakening of the expansion story. The correct framing: a company that enters Thailand and Vietnam profitably in 18 months and arrives in India in Year 4 with regional brand equity is a better acquisition candidate for Hindustan Unilever, Tata Consumer Products, or Coca-Cola India than a company that burned SGD 60M on an unprofitable India entry and has no remaining capital for the Philippines and Vietnam.
            </p>
          </div>

          <p style={{ marginTop: '20px' }}><strong>Expansion Monitoring Dashboard:</strong></p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Metric</th>
                <th>Thailand Target</th>
                <th>Vietnam Target</th>
                <th>Red Line</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Month 6 distribution doors</td>
                <td>&ge; 800 7-Eleven + 60 supermarkets</td>
                <td>&ge; 180 WinMart/Co.op + 30 food service</td>
                <td>Below 50% of target = distribution strategy failing</td>
              </tr>
              <tr>
                <td>Month 6 revenue (SGD M)</td>
                <td>&ge; SGD 1.8M</td>
                <td>&ge; SGD 0.9M</td>
                <td>Below SGD 1.0M (TH) / SGD 0.5M (VN) = pricing or trial issue</td>
              </tr>
              <tr>
                <td>Consumer repeat rate (Month 3&ndash;6)</td>
                <td>&ge; 28%</td>
                <td>&ge; 24%</td>
                <td>Below 18% = product-market fit concern, review positioning</td>
              </tr>
              <tr>
                <td>EBITDA breakeven</td>
                <td>Month 13&ndash;15</td>
                <td>Month 15&ndash;18</td>
                <td>Not achieved by Month 20 (TH) / Month 22 (VN) = review model</td>
              </tr>
              <tr>
                <td>Year 1 investment vs. budget</td>
                <td>&le; SGD 36M</td>
                <td>&le; SGD 30M</td>
                <td>10% over budget triggers CFO review and replan</td>
              </tr>
              <tr>
                <td>India feasibility milestones</td>
                <td colspan="2">FSSAI filing complete Month 6; Mumbai test by Month 12</td>
                <td>Filing not complete by Month 9 = Year 4 India entry at risk</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2>From Someone Who Has Done This Before</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>Why Consumer Brand Expansions Fail at the TAM Stage</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              The single most common cause of capital destruction in consumer brand geographic expansion is the decision to enter a market based on TAM size rather than RSM economics. TAM is a number designed to justify the size of the opportunity to investors. It is not a number designed to guide capital allocation. The two functions are different, and treating them as the same causes companies to enter large markets that they cannot efficiently serve at their current stage of development and capital position. India at USD 14.2B TAM is genuinely attractive. India at USD 9M Year 2 revenue for BrewStar at SGD 63M investment exceeding the budget constraint is genuinely uneconomic. Both statements are true. Only one should drive the capital allocation decision.
            </p>
          </div>
          <div className="highlight-box">
            <strong>How to Tell an Investor That Their Thesis Needs Refinement Without Telling Them They Were Wrong</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Aditya built the Series C thesis around a four-market, 36-month expansion narrative. That narrative is not wrong &mdash; the four markets are the right four markets and the 36-month horizon is broadly correct. What the bottom-up analysis adds is sequencing and capital efficiency. The message to Aditya is not &ldquo;your TAM was misleading&rdquo; &mdash; it is &ldquo;here is the precise execution pathway through the four markets that maximises ROIC and preserves the exit optionality the thesis depends on.&rdquo; The first framing makes Aditya defensive and creates a credibility dispute. The second framing makes Aditya an ally in the refined strategy. Always give an investor a better version of their own thesis rather than a competing thesis. The better version is more credible because it builds on their conviction rather than replacing it.
            </p>
          </div>
          <div className="highlight-box">
            <strong>The 7-Eleven Relationship Is the Single Most Important Commercial Decision in Thailand</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              7-Eleven Thailand operates 14,000 stores with a 24-hour footprint across Bangkok and secondary cities. For a premium RTD brand, national 7-Eleven listing is the equivalent of market launch. But 7-Eleven Thailand does not list brands quickly &mdash; the buyer relationship, product trial process, and planogram approval typically takes 4&ndash;6 months from first meeting to shelf placement. The Country Manager hire must be someone with an existing 7-Eleven Thailand relationship, not someone who needs to build it from scratch. This single hire determines whether BrewStar hits Month 4&ndash;5 first revenue or Month 8&ndash;10 first revenue. The six-month difference is the difference between EBITDA positive in Month 13 and EBITDA positive in Month 19 &mdash; which is the difference between meeting and missing Priscilla&apos;s constraint.
            </p>
          </div>
          <div className="highlight-box">
            <strong>What the Analysis Cannot Tell You About Vietnam</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Vietnam&apos;s first-mover advantage in the mid-premium RTD tier is real and quantifiable in the market sizing. What it cannot quantify is the speed at which the MNCs will respond once BrewStar demonstrates that the tier works. Coca-Cola, Suntory, and Thai Beverage all have Vietnam operations and distribution networks that can reach 200,000 outlets within 12 months of a decision to enter a segment. BrewStar&apos;s first-mover advantage has a window &mdash; probably 18&ndash;24 months before the segment attracts serious MNC attention. The Vietnam strategy must be designed to achieve maximum distribution penetration and consumer brand loyalty within that window, not to grow gradually on the assumption that the competitive landscape stays benign. Move fast or don&apos;t go.
            </p>
          </div>
          <div className="highlight-box">
            <strong>The India Question Priscilla Will Be Asked in Every Board Meeting for the Next Three Years</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              &ldquo;When are we going to India?&rdquo; is the question that will follow Priscilla from every investor interaction until BrewStar either enters India credibly or exits via a strategic sale. The answer she needs is not &ldquo;we have deferred India&rdquo; &mdash; it is &ldquo;we are building toward India systematically: FSSAI filing in Month 6, Mumbai test in Month 12, full Tier 1 city entry in Year 4 funded by Thailand and Vietnam cash flows, with the brand equity and distribution knowledge that makes the India entry succeed rather than burn capital on a premature launch.&rdquo; That answer is analytically correct, investor-credible, and practically actionable. The worst possible outcome is that India becomes a recurring disappointment &mdash; promised and deferred quarter after quarter without a funded execution plan. The FSSAI filing and Mumbai test convert India from a deferred hope into an active program. That distinction is worth the SGD 20M it costs.
            </p>
          </div>
        </div>
      </section>

    </div>
  );
};

export default Case09;
