// ── CASE REGISTRY ────────────────────────────────────────────
// To add a new case: create the JSX file, import it here, add one entry.

import Case01 from './Case01_MarginCollapse.jsx'
import Case02 from './Case02_CustomerExodus.jsx'
import Case03 from './Case03_LastDecadeOfCoal.jsx'
import Case04 from './Case04_UnitEconomicsTrap.jsx'
import Case05 from './Case05_DrugLaunch.jsx'
import Case06 from './Case06_SupplyChain.jsx'
import Case07 from './Case07_LoyaltyParadox.jsx'
import Case08 from './Case08_AcquisitionTrap.jsx'
import Case09 from './Case09_MarketSizing.jsx'
import Case10 from './Case10_OrgExecution.jsx'
import Case11 from './Case11_SystemsThinking';
import Case12 from './Case12_BusinessFluency';
import Case13 from './Case13_DataSense';
import Case14 from './Case14_ExecutiveCommunication';
import Case15 from './Case15_PreliminaryStudy';
import Case16 from './Case16_PreliminaryStudy';
import Case17 from './Case17_CLevelBankingDeck';

export const cases = [
  
  {
    id: 'case-01',
    slug: 'margin-collapse',
    number: '01',
    title: 'The Margin Collapse',
    subtitle: 'When SKU proliferation hollows out the portfolio from inside',
    industry: 'FMCG / Consumer Goods',
    firm: 'BCG',
    framework: 'Profit Tree + BCG Matrix + Price Elasticity',
    decisionType: 'Portfolio Rationalization + Margin Recovery',
    difficulty: 'Advanced',
    region: 'Indonesia',
    readTime: '35 min',
    accentColor: '#C4472A',
    component: Case01,
  },
  {
    id: 'case-02',
    slug: 'customer-exodus',
    number: '02',
    title: 'The Profitable Customer Exodus',
    subtitle: 'When 96% retention hides a collapsing revenue model',
    industry: 'Retail Banking',
    firm: 'McKinsey',
    framework: 'CLV + Cost-to-Serve',
    decisionType: 'Digital Transformation',
    difficulty: 'Advanced',
    region: 'Southeast Asia',
    readTime: '38 min',
    accentColor: '#2A5C8B',
    component: Case02,
  },
  {
    id: 'case-03',
    slug: 'last-decade-of-coal',
    number: '03',
    title: 'The Last Decade of Coal',
    subtitle: 'Retiring assets before the market does it for you',
    industry: 'Energy & Resources',
    firm: 'McKinsey',
    framework: 'Scenario DCF + Portfolio Optimisation',
    decisionType: 'Asset Retirement + Capital Reallocation',
    difficulty: 'Advanced',
    region: 'Australia',
    readTime: '42 min',
    accentColor: '#2E7D52',
    component: Case03,
  },
  {
  id: 'case-04',               // unique, kebab-case
  slug: 'unit-economics-trap', // becomes the URL: /case/unit-economics-trap
  number: '04',                // display number on the card
  title: 'The Unit Economics Trap',
  subtitle: 'When the cohort data says something the investor deck does not',
  industry: 'Tech / SaaS',    // used by the industry filter
  firm: 'Bain',               // used by the firm filter — BCG | McKinsey | Bain
  framework: 'Cohort LTV/CAC + Funnel Decomposition',
  decisionType: 'Restructure or Raise',
  difficulty: 'Advanced',
  region: 'Indonesia / Southeast Asia',
  readTime: '36 min',
  accentColor: '#7B3FC4',     // the top border colour on the card
  component: Case04,          // points to the import above
},
  {
    id: 'case-05',
    slug: 'drug-launch',
    number: '05',
    title: 'The Drug That Cannot Launch Everywhere',
    subtitle: 'When the science is ready but the market is not',
    industry: 'Healthcare & Pharma',
    firm: 'McKinsey',
    framework: 'Patient Journey + Payer Economics',
    decisionType: 'Market Prioritization',
    difficulty: 'Advanced',
    region: 'Asia Pacific',
    readTime: '40 min',
    accentColor: '#C47A2A',
    component: Case05,
  },
  
  {
    id: 'case-06',
    slug: 'supply-chain-broke',
    number: '06',
    title: 'The Supply Chain That Broke',
    subtitle: 'Make, buy, or partner — and which parts of what',
    industry: 'Industrial / Manufacturing',
    firm: 'BCG',
    framework: 'Value Chain + Make-vs-Buy',
    decisionType: 'Vertical Integration',
    difficulty: 'Advanced',
    region: 'Vietnam / Global',
    readTime: '37 min',
    accentColor: '#2A7B8B',
    component: Case06,
  },
  {
    id: 'case-07',
    slug: 'loyalty-paradox',
    number: '07',
    title: 'The Loyalty Paradox',
    subtitle: 'When your best customers cost the most to keep',
    industry: 'Retail (Omnichannel)',
    firm: 'Bain',
    framework: 'NPS + Category Management + CLV',
    decisionType: 'Omnichannel Investment',
    difficulty: 'Advanced',
    region: 'Southeast Asia',
    readTime: '34 min',
    accentColor: '#8B2A5C',
    component: Case07,
  },
  {
    id: 'case-08',
    slug: 'acquisition-trap',
    number: '08',
    title: 'The Acquisition That Should Not Happen',
    subtitle: 'When synergies are stories and the price is certain',
    industry: 'M&A / Private Equity',
    firm: 'McKinsey',
    framework: 'Due Diligence + Synergy Modelling',
    decisionType: 'Buy / Don\'t Buy',
    difficulty: 'Advanced',
    region: 'Global',
    readTime: '41 min',
    accentColor: '#C4472A',
    component: Case08,
  },
  {
    id: 'case-09',
    slug: 'market-sizing',
    number: '09',
    title: 'The Market That Looks Big but Isn\'t',
    subtitle: 'TAM is not your market. Your market is much smaller.',
    industry: 'Consumer / Expansion',
    firm: 'BCG',
    framework: 'Market Sizing + Porter\'s Five Forces',
    decisionType: 'Geographic Expansion',
    difficulty: 'Advanced',
    region: 'South & Southeast Asia',
    readTime: '33 min',
    accentColor: '#5C8B2A',
    component: Case09,
  },
  {
    id: 'case-10',
    slug: 'org-execution',
    number: '10',
    title: 'The Organisation That Cannot Execute',
    subtitle: 'The strategy is right. The structure is killing it.',
    industry: 'Cross-Industry (Post-Merger)',
    firm: 'McKinsey',
    framework: 'McKinsey 7S + Change Readiness',
    decisionType: 'Post-Merger Integration',
    difficulty: 'Advanced',
    region: 'Global',
    readTime: '39 min',
    accentColor: '#8B6B2A',
    component: Case10,
  },
{
    id: 'case-11',
    slug: 'deposit-growth',
    number: '11',
    title: 'The Bank That Cannot Grow Its Deposits',
    subtitle: 'The problem is not the interest rate. It is the system.',
    industry: 'Retail Banking',
    firm: 'Internal BA Team',
    framework: 'Deposit Funnel Analysis + Incentive Mapping',
    decisionType: 'Operational Turnaround',
    difficulty: 'Intermediate',
    region: 'Indonesia (Java & Sumatra)',
    readTime: '28 min',
    accentColor: '#1A5276',
    week: 1,
    skill: 'Systems Thinking',
    deliverable: 'Business Situation Map',
    component: Case11,
  },

  {
    id: 'case-12',
    slug: 'insurance-profit-quality',
    number: '12',
    title: 'The Insurance Company That Looks Healthy But Isn\'t',
    subtitle: 'The headline says profit. The combined ratio says something else.',
    industry: 'General Insurance',
    firm: 'Internal CFO Review',
    framework: 'Combined Ratio Decomposition + Profit Quality Analysis',
    decisionType: 'Strategic Risk Assessment',
    difficulty: 'Intermediate',
    region: 'Indonesia (Jakarta)',
    readTime: '32 min',
    accentColor: '#1E8449',
    week: 2,
    skill: 'Business Fluency',
    deliverable: 'Executive Risk Brief',
    component: Case12,
  },

  {
    id: 'case-13',
    slug: 'lending-conflicting-signals',
    number: '13',
    title: 'The Lending Business With Three Conflicting Signals',
    subtitle: 'Everyone is right. Only one signal predicts the future.',
    industry: 'Consumer Lending / Multifinance',
    firm: 'Internal Risk Review',
    framework: 'Vintage Analysis + Leading vs Lagging Indicators',
    decisionType: 'Credit Committee Decision',
    difficulty: 'Advanced',
    region: 'Indonesia (Surabaya)',
    readTime: '35 min',
    accentColor: '#7D3C98',
    week: 3,
    skill: 'Data Sense',
    deliverable: 'Defensible Decision Memo',
    component: Case13,
  },
  {
    id: 'case-14',
    slug: 'board-executive-communication',
    number: '14',
    title: 'The Board That Needs to Hear Something It Does Not Want to Hear',
    subtitle: 'Three slides. Twenty minutes. One chance to get it right.',
    industry: 'Islamic Banking / Syariah Finance',
    firm: 'Internal Audit Committee Review',
    framework: 'Minto Pyramid (SCR) + Situation-Complication-Resolution',
    decisionType: 'Board-Level Strategic Intervention',
    difficulty: 'Advanced',
    region: 'Indonesia (National)',
    readTime: '38 min',
    accentColor: '#B7410E',
    week: 4,
    skill: 'Executive Communication',
    deliverable: '3-Slide Executive Presentation',
    component: Case14,
  },
  {
  id: 'case-15',
  slug: 'preliminary-study',
  number: '15',           // Displayed as "00" — sits before Case 01
  title: 'Before You Read a Case — How a Business Analyst Actually Thinks',
  subtitle: 'Read this first. Everything else makes more sense after.',
  industry: 'Cross-Industry Foundation',
  firm: 'All Cases',
  framework: 'Problem Structuring + Symptom vs Cause + Framework Selection + Defensible Recommendations + Executive Communication',
  decisionType: 'Foundational Study',
  difficulty: 'Foundational',
  region: 'Cross-Regional',
  readTime: '42 min',
  accentColor: '#2C3E50',   // Charcoal — neutral, foundational, serious
  isPreliminary: true,      // Flag for UI: render with different badge style
  pinned: true,             // Flag for UI: always show first in library
  component: Case15,
},
  {
    id: 'case-16',
    slug: 'subject-matter-primer',
    number: '16',
    title: 'The Subject Matter You Need Before the Cases Make Sense',
    subtitle: 'Read this first. Everything else makes more sense after.',
    industry: 'Cross-Industry Foundation',
    firm: 'All Cases',
    framework: 'P&L · Banking · Insurance · PE · SaaS · Pharma · Supply Chain · Retail · Energy · Consulting',
    decisionType: 'Foundational Study',
    difficulty: 'Foundational',
    region: 'Cross-Regional',
    readTime: '45 min',
    accentColor: '#2C3E50',
    isPreliminary: true,
    pinned: true,
    track: 'foundation',
    component: Case16,
  },
  {
    id: 'case-17',
    slug: 'banking-clevel-deck',
    number: '17',
    title: 'Two Banks. One Diagnosis. One Board.',
    subtitle: 'The retail banking review that connects what the data has been saying all along.',
    industry: 'Retail Banking / Financial Services',
    firm: 'McKinsey',
    framework: 'Minto SCR + CLV Segmentation + Deposit Funnel + Systems Thinking',
    decisionType: 'Board-Level Strategic Intervention',
    difficulty: 'Advanced',
    region: 'Indonesia / Thailand',
    readTime: '30 min',
    accentColor: '#0D3B6E',
    component: Case17,
  },
]

export const getCaseBySlug = (slug) => cases.find(c => c.slug === slug)
export const getCaseById   = (id)   => cases.find(c => c.id === id)
